apiVersion: apps/v1
kind: Deployment

metadata:
   name: backend-deployment
   namespace: chat-app

spec:
    replicas: 3
    selcetors:
       matchLabels:
          app: backend
    template:
      metadata:
        name: backend-pod
        namespace: chat-app
        labels:
           app: backend
      spec:
         conatiners:
            - name: backend
              image: jaishankar7655/node-backend:latest
              ports:
                 - containerPort: 5001
                   env:
                   - name: MONGO_URL
                     value: "mongodb://mongoadmin:secret@mongo:27017/chatapp?authSource=admin"
                   - name: JWT_SECRET
                     value: "dev_secret_key_123"
                   - name: PORT
                     value: "5001"

---

apiVersion: v1
kind: Service
metadata:
    name: backend-service
    namespace: chat-app

spec:
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
           

